AWSTemplateFormatVersion: 2010-09-09
Description: Database Automation Stack    

Parameters:
  
  MasterDbUser:
    Type: String
    Default:  admin

  MasterDbPassword:
    Type: String
    Default: Pass2Word!!01


Resources:

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Database Security Group
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '1433'
        ToPort: '1433'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '3306'
        ToPort: '3306'
        CidrIp: 0.0.0.0/0

  SqlServer:
    DependsOn: SecurityGroup
    Type: AWS::RDS::DBInstance
    Properties:
      VPCSecurityGroups:
        - !Sub ${SecurityGroup.GroupId}
      DBInstanceIdentifier: DB-AUTOMATION-SQLSERVER
      LicenseModel: license-included
      Engine: sqlserver-ex
      EngineVersion: 15.00.4236.7.v1
      MultiAZ: false
      DBInstanceClass: db.t3.small
      AllocatedStorage: "20"
      PubliclyAccessible: true
      MasterUsername: !Ref MasterDbUser
      MasterUserPassword: !Ref MasterDbPassword
      BackupRetentionPeriod: 1

  MySql:
    Type: AWS::RDS::DBInstance
    Properties:
      VPCSecurityGroups:
        - !Sub ${SecurityGroup.GroupId}
      DBInstanceIdentifier: DB-AUTOMATION-MYSQL
      AllocatedStorage: "20"
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      BackupRetentionPeriod: 1
      DBInstanceClass: db.t4g.micro
      Engine: mysql
      EngineVersion: 8.0.28
      MultiAZ: false
      PubliclyAccessible: true
      MasterUsername: !Ref MasterDbUser
      MasterUserPassword: !Ref MasterDbPassword

  SqlServerHostParameter:
    DependsOn: SqlServer
    Type:  AWS::SSM::Parameter
    Properties:
      Name: db-automation-sql-server-host
      Type: String
      Value: !Sub ${SqlServer.Endpoint.Address}

  SqlServerPortParameter:
    DependsOn: SqlServer
    Type:  AWS::SSM::Parameter
    Properties:
      Name: db-automation-sql-server-port
      Type: String
      Value: !Sub ${SqlServer.Endpoint.Port}

  MySqlHostParameter:
    DependsOn: MySql
    Type:  AWS::SSM::Parameter
    Properties:
      Name: db-automation-mysql-host
      Type: String
      Value: !Sub ${MySql.Endpoint.Address}

  MySqlPortParameter:
    DependsOn: MySql
    Type:  AWS::SSM::Parameter
    Properties:
      Name: db-automation-mysql-port
      Type: String
      Value: !Sub ${MySql.Endpoint.Port}

  MasterUserParameter:
    Type:  AWS::SSM::Parameter
    Properties:
      Name: db-automation-user
      Type: String
      Value: !Ref MasterDbUser

  MasterPasswordParameter:
    DependsOn: MySql
    Type:  AWS::SSM::Parameter
    Properties:
      Name: db-automation-password
      Type: String
      Value: !Ref MasterDbPassword


Outputs:
   SQLDatabaseEndpoint:
     Description: SQL Server Database endpoint
     Value: !Sub "${SqlServer.Endpoint.Address}:${SqlServer.Endpoint.Port}"

   MySqlDatabaseEndpoint:
     Description: MySql Database endpoint
     Value: !Sub "${MySql.Endpoint.Address}:${MySql.Endpoint.Port}"