AWSTemplateFormatVersion: 2010-09-09
Description: Database Automation Stack    

Resources:

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Database Security Group
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '1433'
        ToPort: '1433'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '3306'
        ToPort: '3306'
        CidrIp: 0.0.0.0/0

  SqlServer:
    DependsOn: SecurityGroup
    Type: AWS::RDS::DBInstance
    Properties:
      VPCSecurityGroups:
        - !Sub ${SecurityGroup.GroupId}
      DBInstanceIdentifier: DB-AUTOMATION-SQLSERVER
      LicenseModel: license-included
      Engine: sqlserver-se
      EngineVersion: 15.00.4236.7.v1
      MultiAZ: false
      DBInstanceClass: db.t4g.micro
      AllocatedStorage: "20"
      PubliclyAccessible: true
      MasterUsername: 'admin'
      MasterUserPassword: 'Pass2Word!!01'
      BackupRetentionPeriod: 1


Outputs:
   SQLDatabaseEndpoint:
     Description: Database endpoint
     Value: !Sub "${SqlServer.Endpoint.Address}:${SQLDatabase.Endpoint.Port}"