version: '3.3'

services:

  db:
    container_name: mysql
    build: .
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ../skeema/schemas:/var/schemas
