name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

variables:

  - name: projectDirectory
    value: $(System.DefaultWorkingDirectory)/skeema
  - name: 

stages:
  - stage: deployDatabase
    displayName: Deploy Database Changes
    jobs:
      - job: skeema
        displayName: Run Skeema
        workspace:
          clean: all
        steps:
          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: Update .skeema Config
            inputs:
              targetFiles: |
                $(projectDirectory)/schemas/.skeema

