name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

variables:

  - name: projectDirectory
    value: $(System.DefaultWorkingDirectory)/skeema
  - name: region
    value: us-east-2
  - name: DbHost
  - name: DbPort
  - name: DbUser
  - name: DbPassword

stages:
  - stage: deployDatabase
    displayName: Deploy Database Changes
    jobs:
      - job: skeema
        displayName: Run Skeema Diff and Deploy
        workspace:
          clean: all
        steps:
          - task: AWSShellScript@1
            displayName: Update Pipeline Variables
            inputs:
              awsCredentials: "AWS"
              regionName: "$(region)"
              scriptType: "inline"
              inlineScript: |
                host=`aws ssm get-parameter --name db-automation-mysql-host --region $(region) --query "Parameter.Value" --output text`
                port=`aws ssm get-parameter --name db-automation-mysql-port --region $(region) --query "Parameter.Value" --output text`
                user=`aws ssm get-parameter --name db-automation-user --region $(region) --query "Parameter.Value" --output text`
                password=`aws ssm get-parameter --name db-automation-password --region $(region) --query "Parameter.Value" --output text`

                echo "##vso[task.setvariable variable=DbHost;]$host"
                echo "##vso[task.setvariable variable=DbPort;]$port"
                echo "##vso[task.setvariable variable=DbUser;]$user"
                echo "##vso[task.setvariable variable=DbPassword;]$password"

          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: Update .skeema Deploy Config
            inputs:
              targetFiles: |
                $(projectDirectory)/schemas/.skeema

          - task: Bash@3 
            displayName: Apply Skeema Diff
            inputs:
              workingDirectory: $(projectDirectory)/schemas
              script: |
                skeema diff deploy
                skeema push deploy
            
