name: deploy

on:
  push:
    branches:
      - main
      - github
permissions:
  id-token: write
  contents: read
  actions: read
jobs:
  deployDev:
    name: Deploy Dev
    runs-on: self-hosted
    environment: dev
    env:
      dbHost:
      dbPort:
      dbUser:
      dbPwd:
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
      - name: Get Database Credentials
        shell: bash
        run: |
          dbHost=`aws ssm get-parameter --name db-automation-mysql-host --query "Parameter.Value" --output text`
          dbPort=`aws ssm get-parameter --name db-automation-mysql-port --query "Parameter.Value" --output text`
          dbUser=`aws secretsmanager get-secret-value --secret-id db-automation-mysql-user --query "SecretString" --output text`
          dbPwd=`aws secretsmanager get-secret-value --secret-id db-automation-mysql-password --query "SecretString" --output text`
      - name: Replace Tokens in .skeema config
        uses: cschleiden/replace-tokens@v1
        with:
          files: './skeema/schemas/.skeema'
      - name: View
        run: cat ./skeema/schemas/.skeema
        env:
          HOST: ${{ env.dbHost }}
          PORT: ${{ env.dbPort }}
          USER: ${{ env.dbUser }}
          PASSWORD: ${{ env.dbPwd }}
